name: Build Binary R Package

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Name of the R package"
        required: true
        type: string
      os:
        description: "Target OS for binary package"
        required: true
        type: choice
        options:
          - windows
          - macOS
      dependencies:
        description: "Comma-separated list of dependencies (optional)"
        required: false
        type: string

jobs:
  build-r-package:
    runs-on: ${{ inputs.os == 'windows' && 'windows-latest' || 'macos-latest' }}
    outputs:
      artifact: ${{ steps.upload.outputs.artifact_name }}

    steps:
      - name: Install Rust GNU Toolchain (Windows only)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          rustup toolchain install stable-x86_64-pc-windows-gnu
          rustup default stable-x86_64-pc-windows-gnu
          rustup target add x86_64-pc-windows-gnu
          echo "CARGO_BUILD_TARGET=x86_64-pc-windows-gnu" >> $GITHUB_ENV

      - name: Set up environment
        shell: bash
        run: |
          echo "PACKAGE_NAME=${{ inputs.package_name }}" >> $GITHUB_ENV
          echo "PACKAGE_URL=https://dahl.byu.edu/r/src/contrib/${{ inputs.package_name }}.tar.gz" >> $GITHUB_ENV
          echo "DEPENDENCIES=${{ inputs.dependencies }}" >> $GITHUB_ENV

      - name: Debug Variables
        shell: bash
        run: |
          echo "PACKAGE_NAME: $PACKAGE_NAME"
          echo "PACKAGE_URL: $PACKAGE_URL"
          echo "DEPENDENCIES: $DEPENDENCIES"
          echo "CARGO_BUILD_TARGET: $CARGO_BUILD_TARGET"

      - name: Download Source Package
        shell: bash
        run: |
          curl -o "${PACKAGE_NAME}.tar.gz" "${PACKAGE_URL}"

      - name: Set Up R Environment
        uses: r-lib/actions/setup-r@v2

      - name: Install Dependencies
        shell: bash
        run: |
          deps=$(echo "${DEPENDENCIES}" | tr ',' ' ')
          for pkg in $deps
          do
            Rscript -e "install.packages('$pkg', repos = c('https://dahl.byu.edu/r', 'https://cloud.r-project.org'))"
          done

      - name: Build Binary Package
        shell: bash
        run: |
          R CMD INSTALL --build ${PACKAGE_NAME}.tar.gz

      - name: Upload Binary R Package
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            ${{ env.PACKAGE_NAME }}*.tgz
            ${{ env.PACKAGE_NAME }}*.zip
          retention-days: 1

