name: Build R Binaries

on:
  push:
    paths:
      - "src/contrib/*.tar.gz"
    branches:
      - main

jobs:
  build:
    name: Build R Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    outputs:
      macos_artifact: ${{ steps.upload_macos.outputs.artifact_name }}
      windows_artifact: ${{ steps.upload_windows.outputs.artifact_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'

      - name: Install Dependencies
        run: |
          install.packages(c("mclust"))
        shell: Rscript {0}

      - name: Find the Latest Source Package
        id: find_source
        run: |
          latest_pkg <- list.files("src/contrib", pattern = "\\.tar\\.gz$", full.names = TRUE)
          latest_pkg <- latest_pkg[order(file.info(latest_pkg)$mtime, decreasing = TRUE)][1]
          cat(sprintf("SRC_PACKAGE=%s\n", latest_pkg), file = Sys.getenv("GITHUB_ENV"), append = TRUE)
        shell: Rscript {0}

      - name: Build Binary
        run: |
          R CMD INSTALL --build "${{ env.SRC_PACKAGE }}"
        shell: bash

      - name: Upload macOS Binary
        if: matrix.os == 'macos-latest'
        id: upload_macos
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: "*.tgz"
          retention-days: 1

      - name: Upload Windows Binary
        if: matrix.os == 'windows-latest'
        id: upload_windows
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: "*.zip"
          retention-days: 1

