name: Build Binary R Package

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Name of the R package"
        required: true
        type: string
      os:
        description: "Target OS for binary package"
        required: true
        type: choice
        options:
          - windows
          - macOS
      dependencies:
        description: "Comma-separated list of dependencies (optional)"
        required: false
        type: string

jobs:
  build-r-package:
    runs-on: ${{ inputs.os == 'windows' && 'windows-latest' || 'macos-latest' }}
    outputs:
      artifact: ${{ steps.upload.outputs.artifact_name }}

    steps:
      - name: Set up environment
        run: |
          echo "PACKAGE_NAME=${{ inputs.package_name }}" >> $GITHUB_ENV
          echo "OS=${{ inputs.os }}" >> $GITHUB_ENV
          echo "DEPENDENCIES=${{ inputs.dependencies }}" >> $GITHUB_ENV

      - name: Construct Source Package URL
        run: |
          echo "PACKAGE_URL=https://dahl.byu.edu/r/src/contrib/${PACKAGE_NAME}.tar.gz" >> $GITHUB_ENV

      - name: Download Source Package
        run: |
          curl -o ${PACKAGE_NAME}.tar.gz ${PACKAGE_URL}
        shell: bash

      - name: Set Up R Environment
        uses: r-lib/actions/setup-r@v2

      - name: Install Dependencies
        if: env.DEPENDENCIES != ''
        run: |
          Rscript -e '
            repos <- c("https://dahl.byu.edu/r", "https://cloud.r-project.org");
            deps <- unlist(strsplit(gsub(" ", "", Sys.getenv("DEPENDENCIES")), ",")); 
            install.packages(deps, repos = repos, dependencies = TRUE)'
        shell: bash

      - name: Build Binary Package
        run: |
          R CMD INSTALL --build ${PACKAGE_NAME}.tar.gz
        shell: bash

      - name: Upload Binary R Package
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            ${{ env.PACKAGE_NAME }}*.tgz
            ${{ env.PACKAGE_NAME }}*.zip
          retention-days: 1

